config/routes.rb
Newapp::Application.routes.draw do
  
  get "plivo/send_msg"

  get "/event_participations", to: "event_participations#index", as: :event_participations
  get "event_participations/index"
  get "event_participations/edit"
  get "event_participations/update"

  get "admin/index"
  get "/admin", :to => "admin#index", :as => :admin
  get "/home", :to => "events#index", :as => :home
  get "/events", :to => "events#index", :as => :home
  get "/profile", :to => "users#profile", :as => :profile
  get "/my_certifications", :to => "users#certifications", :as => :my_certifications
  get "/my_assets", :to => "users#assets", :as => :my_assets

  resources :paths

  resources :certifications

  resources :certification_assertions

  resources :users do
    member do
      post :add_certification
    end
  end

  resources :categories

  resources :events

  resources :skills

  resources :physical_assets

  get "users/sign_up"

  get   '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

   root :to => 'users#profile'

end

app/views/admin/index.html.erb
<h1>Administrative Tasks</h1>
<p>Here are links to help get some stuff administered:</p>

<p><%= link_to "Assets", physical_assets_path %></p>

<p><%= link_to "Categories", categories_path %></p>

<p><%= link_to "Certifications", certifications_path %></p>

<p><%= link_to "Certification Approvals", certification_assertions_path %></p>

<p><%= link_to "Events", events_path %></p>

<p><%= link_to "Event Participation Verification", event_participations_path %></p>

<p><%= link_to "Paths", paths_path %></p>

<p><%= link_to "Skills", skills_path %></p>

<p><%= link_to "Users", users_path %></p>