config/routes.rb
Newapp::Application.routes.draw do
  
  get "plivo/send_msg"

  get "/event_participations", to: "event_participations#index", as: :event_participations
  get "event_participations/index"
  get "event_participations/edit"
  get "event_participations/update"

  get "admin/index"
  get "/admin", :to => "admin#index", :as => :admin
  get "/home", :to => "events#index", :as => :home
  get "/events", :to => "events#index", :as => :home
  get "/profile", :to => "users#profile", :as => :profile
  get "/my_certifications", :to => "users#certifications", :as => :my_certifications
  get "/my_assets", :to => "users#assets", :as => :my_assets

  resources :paths

  resources :certifications

  resources :certification_assertions

  resources :users do
    member do
      post :add_certification
    end
  end

  resources :categories

  resources :events

  resources :skills

  resources :physical_assets

  get "users/sign_up"

  get   '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

   root :to => 'users#profile'

end

app/models/physical_asset.rb
class PhysicalAsset < ActiveRecord::Base
  attr_accessible :name, :category_id
  belongs_to :category
end

app/controllers/physical_assets_controller.rb
class PhysicalAssetsController < ApplicationController
  # GET /physical_assets
  # GET /physical_assets.json
  def index
    @physical_assets = PhysicalAsset.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @physical_assets }
    end
  end

  # GET /physical_assets/1
  # GET /physical_assets/1.json
  def show
    @physical_asset = PhysicalAsset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @physical_asset }
    end
  end

  # GET /physical_assets/new
  # GET /physical_assets/new.json
  def new
    @physical_asset = PhysicalAsset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @physical_asset }
    end
  end

  # GET /physical_assets/1/edit
  def edit
    @physical_asset = PhysicalAsset.find(params[:id])
  end

  # POST /physical_assets
  # POST /physical_assets.json
  def create
    @physical_asset = PhysicalAsset.new(params[:physical_asset])

    respond_to do |format|
      if @physical_asset.save
        format.html { redirect_to @physical_asset, notice: 'Physical asset was successfully created.' }
        format.json { render json: @physical_asset, status: :created, location: @physical_asset }
      else
        format.html { render action: "new" }
        format.json { render json: @physical_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /physical_assets/1
  # PUT /physical_assets/1.json
  def update
    @physical_asset = PhysicalAsset.find(params[:id])

    respond_to do |format|
      if @physical_asset.update_attributes(params[:physical_asset])
        format.html { redirect_to @physical_asset, notice: 'Physical asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @physical_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physical_assets/1
  # DELETE /physical_assets/1.json
  def destroy
    @physical_asset = PhysicalAsset.find(params[:id])
    @physical_asset.destroy

    respond_to do |format|
      format.html { redirect_to physical_assets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/physical_assets_helper.rb
module PhysicalAssetsHelper
  def physical_asset_categories
    Category.find_all_by_area("Physical Assets", order: :name)
  end

  def physical_asset_category_selections
    options_for_select(physical_asset_categories.map{|c|[c.name,c.id]})
  end
end

app/views/physical_assets/_form.html.erb
<%= form_for(@physical_asset) do |f| %>
  <% if @physical_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physical_asset.errors.count, "error") %> prohibited this physical_asset from being saved:</h2>

      <ul>
      <% @physical_asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, physical_asset_category_selections %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physical_assets/edit.html.erb
<h1>Editing physical_asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @physical_asset %> |
<%= link_to 'Back', physical_assets_path %>

app/views/physical_assets/index.html.erb
<h1>Listing physical_assets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @physical_assets.each do |physical_asset| %>
  <tr>
    <td><%= physical_asset.name %></td>
    <td><%= physical_asset.category.name %></td>
    <td><%= link_to 'Show', physical_asset %></td>
    <td><%= link_to 'Edit', edit_physical_asset_path(physical_asset) %></td>
    <td><%= link_to 'Destroy', physical_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Physical asset', new_physical_asset_path %>

app/views/physical_assets/new.html.erb
<h1>New physical_asset</h1>

<%= render 'form' %>

<%= link_to 'Back', physical_assets_path %>

app/views/physical_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @physical_asset.name %>
</p>

<p>
  <b>Category:</b>
  <%= @physical_asset.category.name %>
</p>


<%= link_to 'Edit', edit_physical_asset_path(@physical_asset) %> |
<%= link_to 'Back', physical_assets_path %>