config/routes.rb
Newapp::Application.routes.draw do
  
  get "plivo/send_msg"

  get "/event_participations", to: "event_participations#index", as: :event_participations
  get "event_participations/index"
  get "event_participations/edit"
  get "event_participations/update"

  get "admin/index"
  get "/admin", :to => "admin#index", :as => :admin
  get "/home", :to => "events#index", :as => :home
  get "/events", :to => "events#index", :as => :home
  get "/profile", :to => "users#profile", :as => :profile
  get "/my_certifications", :to => "users#certifications", :as => :my_certifications
  get "/my_assets", :to => "users#assets", :as => :my_assets

  resources :paths

  resources :certifications

  resources :certification_assertions

  resources :users do
    member do
      post :add_certification
    end
  end

  resources :categories

  resources :events

  resources :skills

  resources :physical_assets

  get "users/sign_up"

  get   '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

   root :to => 'users#profile'

end

app/models/certification.rb
class Certification < ActiveRecord::Base
  attr_accessible :description, :fee, :name, :path_id, :prerequisite_id, :time_in_minutes
  has_many :certification_assertions
  has_many :pending_holders, through: :certification_assertions, conditions: {is_verified: false}
  has_many :verified_holders, through: :certification_assertions, conditions: {is_verified: true}
  belongs_to :path
  belongs_to :prerequisite, :class_name => "Certification"

  # local user only, for now
  attr_accessible :belongs_to_user
  attr_accessor :belongs_to_user

  def full_display
    return { "name" => name,
      "description" => description,
      "id" => id,
      "path_id" => path_id,
      "time_in_minutes" => time_in_minutes,
      "prerequisite_id" => prerequisite_id,
      "belongs_to_user" => belongs_to_user || false
    }
  end
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  # GET /certifications
  # GET /certifications.json
  def index
    @certifications = Certification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @certifications }
    end
  end

  # GET /certifications/1
  # GET /certifications/1.json
  def show
    @certification = Certification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @certification }
    end
  end

  # GET /certifications/new
  # GET /certifications/new.json
  def new
    @certification = Certification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @certification }
    end
  end

  # GET /certifications/1/edit
  def edit
    @certification = Certification.find(params[:id])
  end

  # POST /certifications
  # POST /certifications.json
  def create
    @certification = Certification.new(params[:certification])

    respond_to do |format|
      if @certification.save
        format.html { redirect_to @certification, notice: 'Certification was successfully created.' }
        format.json { render json: @certification, status: :created, location: @certification }
      else
        format.html { render action: "new" }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /certifications/1
  # PUT /certifications/1.json
  def update
    @certification = Certification.find(params[:id])

    respond_to do |format|
      if @certification.update_attributes(params[:certification])
        format.html { redirect_to @certification, notice: 'Certification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certifications/1
  # DELETE /certifications/1.json
  def destroy
    @certification = Certification.find(params[:id])
    @certification.destroy

    respond_to do |format|
      format.html { redirect_to certifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/certifications_helper.rb
module CertificationsHelper
  def prerequisite_selections(target=nil)
    conditions = nil
    if target && !target.new_record?
      conditions = ["id <> ?", target.id]
    end
    Certification.all(order: :name, conditions: conditions).map{|p|[p.name,p.id]}
  end
end

app/views/certifications/_form.html.erb
<%= form_for(@certification) do |f| %>
  <% if @certification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certification.errors.count, "error") %> prohibited this certification from being saved:</h2>

      <ul>
      <% @certification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :time_in_minutes %><br />
    <%= f.number_field :time_in_minutes %>
  </div>
  <div class="field">
    <%= f.label :fee %><br />
    <%= f.text_field :fee %>
  </div>
  <div class="field">
    <%= f.label :path_id %><br />
    <%= f.select :path_id, path_selections %>
  </div>
  <div class="field">
    <%= f.label :prerequisite_id %><br />
    <%= f.select :prerequisite_id, prerequisite_selections(f.object), include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certifications/index.html.erb
<h1>Listing certifications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Hours</th>
    <th>Fee</th>
    <th>Path</th>
    <th>Prerequisite</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @certifications.each do |certification| %>
  <tr>
    <td><%= certification.name %></td>
    <td><%= certification.description %></td>
    <td><%= certification.time_in_minutes %></td>
    <td><%= number_to_currency(certification.fee) %></td>
    <td><%= certification.path.name %></td>
    <td><%= certification.prerequisite.try(:name) %></td>
    <td><%= link_to 'Show', certification %></td>
    <td><%= link_to 'Edit', edit_certification_path(certification) %></td>
    <td><%= link_to 'Destroy', certification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Certification', new_certification_path %>

app/views/certifications/new.html.erb
<h1>New certification</h1>

<%= render 'form' %>

<%= link_to 'Back', certifications_path %>

app/views/certifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @certification.name %>
</p>

<p>
  <b>Description:</b>
  <%= @certification.description %>
</p>

<p>
  <b>Time in minutes:</b>
  <%= @certification.time_in_minutes %>
</p>

<p>
  <b>Fee:</b>
  <%= number_to_currency(@certification.fee) %>
</p>

<p>
  <b>Path:</b>
  <%= @certification.path.name %>
</p>

<p>
  <b>Prerequisite:</b>
  <%= @certification.prerequisite.try(:name) %>
</p>


<%= link_to 'Edit', edit_certification_path(@certification) %> |
<%= link_to 'Back', certifications_path %>